/**
 * Tensorflight API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

/**
 * GeoJSon geometry
 */
export interface Polygon extends models.Geometry {
    coordinates?: Array<Array<models.Point2D>>;

}
export namespace Polygon {
}
